# Generated by Django 5.2.1 on 2025-05-27 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('va_bca', 'BCA Virtual Account'), ('va_mandiri', 'Mandiri Virtual Account'), ('va_bni', 'BNI Virtual Account'), ('bank_transfer', 'Transfer Bank'), ('qris', 'QRIS')], default='bank_transfer', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('processing', 'Sedang Diproses'), ('completed', 'Lunas'), ('expired', 'Kadaluarsa'), ('failed', 'Gagal')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='virtual_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.booking'),
        ),
    ]
