# Generated by Django 5.2.1 on 2025-05-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_is_confirmed_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, help_text='Catatan untuk pembayaran (jika ada)', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('processing', 'Menunggu Verifikasi'), ('completed', 'Lunas'), ('expired', 'Kadaluarsa'), ('failed', 'Ditolak')], default='pending', max_length=20),
        ),
    ]
