# Generated by Django 5.2.1 on 2025-05-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_notes_payment_payment_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_proof',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_confirmation_code',
            field=models.CharField(blank=True, help_text='Kode konfirmasi pembayaran', max_length=50, null=True),
        ),
    ]
