# Generated by Django 5.2.1 on 2025-05-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Centang untuk menampilkan lapangan di daftar booking'),
        ),
    ]
