# Generated by Django 5.2.1 on 2025-05-29 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_field_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closure_date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='fields.field')),
            ],
            options={
                'ordering': ['-closure_date'],
                'unique_together': {('field', 'closure_date')},
            },
        ),
    ]
