# Generated by Django 5.2.1 on 2025-05-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Dibatalkan'),
        ),
    ]
