# Generated by Django 5.2.1 on 2025-05-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total Harga'),
        ),
    ]
