# Generated by Django 5.2.1 on 2025-05-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('nama_pengelola', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('futsal', 'Futsal'), ('basket', 'Basket'), ('badminton', 'Badminton'), ('voli', 'Voli')], max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='field_images/')),
                ('default_price', models.PositiveIntegerField(help_text='Harga per jam dalam Rupiah')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Validasi'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement_letter', models.FileField(upload_to='documents/')),
                ('ownership_proof', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
