# Generated by Django 5.2.1 on 2025-05-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldsubmission',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
